
export interface Surah {
  id: number;
  revelation_place: string;
  revelation_order: number;
  bismillah_pre: boolean;
  name_simple: string;
  name_complex: string;
  name_arabic: string;
  verses_count: number;
  pages: number[];
  translated_name: {
    language_name: string;
    name: string;
  };
}

export interface Reciter {
  id: number;
  reciter_name: string;
  style: string | null;
  translated_name: {
    language_name: string;
    name: string;
  };
}

export const SURAHS: Surah[] = [
  { id: 1, name_arabic: "الفاتحة", name_simple: "Al-Fatihah", verses_count: 7, revelation_place: "makkah", revelation_order: 5, bismillah_pre: false, name_complex: "Al-Fātiḥah", pages: [1, 1], translated_name: { language_name: "arabic", name: "الفاتحة" } },
  { id: 2, name_arabic: "البقرة", name_simple: "Al-Baqarah", verses_count: 286, revelation_place: "madinah", revelation_order: 87, bismillah_pre: true, name_complex: "Al-Baqarah", pages: [2, 49], translated_name: { language_name: "arabic", name: "البقرة" } },
  { id: 3, name_arabic: "آل عمران", name_simple: "Ali 'Imran", verses_count: 200, revelation_place: "madinah", revelation_order: 89, bismillah_pre: true, name_complex: "Āli 'Imrān", pages: [50, 76], translated_name: { language_name: "arabic", name: "آل عمران" } },
  { id: 4, name_arabic: "النساء", name_simple: "An-Nisa", verses_count: 176, revelation_place: "madinah", revelation_order: 92, bismillah_pre: true, name_complex: "An-Nisā", pages: [77, 106], translated_name: { language_name: "arabic", name: "النساء" } },
  { id: 5, name_arabic: "المائدة", name_simple: "Al-Ma'idah", verses_count: 120, revelation_place: "madinah", revelation_order: 112, bismillah_pre: true, name_complex: "Al-Mā'idah", pages: [106, 127], translated_name: { language_name: "arabic", name: "المائدة" } },
  { id: 6, name_arabic: "الأنعام", name_simple: "Al-An'am", verses_count: 165, revelation_place: "makkah", revelation_order: 55, bismillah_pre: true, name_complex: "Al-An'ām", pages: [128, 150], translated_name: { language_name: "arabic", name: "الأنعام" } },
  { id: 7, name_arabic: "الأعراف", name_simple: "Al-A'raf", verses_count: 206, revelation_place: "makkah", revelation_order: 39, bismillah_pre: true, name_complex: "Al-A'rāf", pages: [151, 176], translated_name: { language_name: "arabic", name: "الأعراف" } },
  { id: 8, name_arabic: "الأنفال", name_simple: "Al-Anfal", verses_count: 75, revelation_place: "madinah", revelation_order: 88, bismillah_pre: true, name_complex: "Al-Anfāl", pages: [177, 186], translated_name: { language_name: "arabic", name: "الأنفال" } },
  { id: 9, name_arabic: "التوبة", name_simple: "At-Tawbah", verses_count: 129, revelation_place: "madinah", revelation_order: 113, bismillah_pre: false, name_complex: "At-Tawbah", pages: [187, 207], translated_name: { language_name: "arabic", name: "التوبة" } },
  { id: 10, name_arabic: "يونس", name_simple: "Yunus", verses_count: 109, revelation_place: "makkah", revelation_order: 51, bismillah_pre: true, name_complex: "Yūnus", pages: [208, 221], translated_name: { language_name: "arabic", name: "يونس" } },
  { id: 11, name_arabic: "هود", name_simple: "Hud", verses_count: 123, revelation_place: "makkah", revelation_order: 52, bismillah_pre: true, name_complex: "Hūd", pages: [221, 235], translated_name: { language_name: "arabic", name: "هود" } },
  { id: 12, name_arabic: "يوسف", name_simple: "Yusuf", verses_count: 111, revelation_place: "makkah", revelation_order: 53, bismillah_pre: true, name_complex: "Yūsuf", pages: [235, 248], translated_name: { language_name: "arabic", name: "يوسف" } },
  { id: 13, name_arabic: "الرعد", name_simple: "Ar-Ra'd", verses_count: 43, revelation_place: "madinah", revelation_order: 96, bismillah_pre: true, name_complex: "Ar-Ra'd", pages: [249, 255], translated_name: { language_name: "arabic", name: "الرعد" } },
  { id: 14, name_arabic: "إبراهيم", name_simple: "Ibrahim", verses_count: 52, revelation_place: "makkah", revelation_order: 72, bismillah_pre: true, name_complex: "Ibrāhīm", pages: [255, 261], translated_name: { language_name: "arabic", name: "إبراهيم" } },
  { id: 15, name_arabic: "الحجر", name_simple: "Al-Hijr", verses_count: 99, revelation_place: "makkah", revelation_order: 54, bismillah_pre: true, name_complex: "Al-Ḥijr", pages: [262, 267], translated_name: { language_name: "arabic", name: "الحجر" } },
  { id: 16, name_arabic: "النحل", name_simple: "An-Nahl", verses_count: 128, revelation_place: "makkah", revelation_order: 70, bismillah_pre: true, name_complex: "An-Naḥl", pages: [267, 281], translated_name: { language_name: "arabic", name: "النحل" } },
  { id: 17, name_arabic: "الإسراء", name_simple: "Al-Isra", verses_count: 111, revelation_place: "makkah", revelation_order: 50, bismillah_pre: true, name_complex: "Al-Isrā", pages: [282, 293], translated_name: { language_name: "arabic", name: "الإسراء" } },
  { id: 18, name_arabic: "الكهف", name_simple: "Al-Kahf", verses_count: 110, revelation_place: "makkah", revelation_order: 69, bismillah_pre: true, name_complex: "Al-Kahf", pages: [293, 304], translated_name: { language_name: "arabic", name: "الكهف" } },
  { id: 19, name_arabic: "مريم", name_simple: "Maryam", verses_count: 98, revelation_place: "makkah", revelation_order: 44, bismillah_pre: true, name_complex: "Maryam", pages: [305, 312], translated_name: { language_name: "arabic", name: "مريم" } },
  { id: 20, name_arabic: "طه", name_simple: "Taha", verses_count: 135, revelation_place: "makkah", revelation_order: 45, bismillah_pre: true, name_complex: "Ṭāhā", pages: [312, 321], translated_name: { language_name: "arabic", name: "طه" } },
  { id: 21, name_arabic: "الأنبياء", name_simple: "Al-Anbya", verses_count: 112, revelation_place: "makkah", revelation_order: 73, bismillah_pre: true, name_complex: "Al-Anbyā", pages: [322, 331], translated_name: { language_name: "arabic", name: "الأنبياء" } },
  { id: 22, name_arabic: "الحج", name_simple: "Al-Hajj", verses_count: 78, revelation_place: "madinah", revelation_order: 103, bismillah_pre: true, name_complex: "Al-Ḥajj", pages: [332, 341], translated_name: { language_name: "arabic", name: "الحج" } },
  { id: 23, name_arabic: "المؤمنون", name_simple: "Al-Mu'minun", verses_count: 118, revelation_place: "makkah", revelation_order: 74, bismillah_pre: true, name_complex: "Al-Mu'minūn", pages: [342, 349], translated_name: { language_name: "arabic", name: "المؤمنون" } },
  { id: 24, name_arabic: "النور", name_simple: "An-Nur", verses_count: 64, revelation_place: "madinah", revelation_order: 102, bismillah_pre: true, name_complex: "An-Nūr", pages: [350, 359], translated_name: { language_name: "arabic", name: "النور" } },
  { id: 25, name_arabic: "الفرقان", name_simple: "Al-Furqan", verses_count: 77, revelation_place: "makkah", revelation_order: 42, bismillah_pre: true, name_complex: "Al-Furqān", pages: [359, 366], translated_name: { language_name: "arabic", name: "الفرقان" } },
  { id: 26, name_arabic: "الشعراء", name_simple: "Ash-Shu'ara", verses_count: 227, revelation_place: "makkah", revelation_order: 47, bismillah_pre: true, name_complex: "Ash-Shu'arā", pages: [367, 376], translated_name: { language_name: "arabic", name: "الشعراء" } },
  { id: 27, name_arabic: "النمل", name_simple: "An-Naml", verses_count: 93, revelation_place: "makkah", revelation_order: 48, bismillah_pre: true, name_complex: "An-Naml", pages: [377, 385], translated_name: { language_name: "arabic", name: "النمل" } },
  { id: 28, name_arabic: "القصص", name_simple: "Al-Qasas", verses_count: 88, revelation_place: "makkah", revelation_order: 49, bismillah_pre: true, name_complex: "Al-Qaṣaṣ", pages: [385, 396], translated_name: { language_name: "arabic", name: "القصص" } },
  { id: 29, name_arabic: "العنكبوت", name_simple: "Al-'Ankabut", verses_count: 69, revelation_place: "makkah", revelation_order: 85, bismillah_pre: true, name_complex: "Al-'Ankabūt", pages: [396, 404], translated_name: { language_name: "arabic", name: "العنكبوت" } },
  { id: 30, name_arabic: "الروم", name_simple: "Ar-Rum", verses_count: 60, revelation_place: "makkah", revelation_order: 84, bismillah_pre: true, name_complex: "Ar-Rūm", pages: [404, 410], translated_name: { language_name: "arabic", name: "الروم" } },
  { id: 31, name_arabic: "لقمان", name_simple: "Luqman", verses_count: 34, revelation_place: "makkah", revelation_order: 57, bismillah_pre: true, name_complex: "Luqmān", pages: [411, 414], translated_name: { language_name: "arabic", name: "لقمان" } },
  { id: 32, name_arabic: "السجدة", name_simple: "As-Sajdah", verses_count: 30, revelation_place: "makkah", revelation_order: 75, bismillah_pre: true, name_complex: "As-Sajdah", pages: [415, 417], translated_name: { language_name: "arabic", name: "السجدة" } },
  { id: 33, name_arabic: "الأحزاب", name_simple: "Al-Ahzab", verses_count: 73, revelation_place: "madinah", revelation_order: 90, bismillah_pre: true, name_complex: "Al-Aḥzāb", pages: [418, 427], translated_name: { language_name: "arabic", name: "الأحزاب" } },
  { id: 34, name_arabic: "سبأ", name_simple: "Saba", verses_count: 54, revelation_place: "makkah", revelation_order: 58, bismillah_pre: true, name_complex: "Saba", pages: [428, 434], translated_name: { language_name: "arabic", name: "سبأ" } },
  { id: 35, name_arabic: "فاطر", name_simple: "Fatir", verses_count: 45, revelation_place: "makkah", revelation_order: 43, bismillah_pre: true, name_complex: "Fāṭir", pages: [434, 440], translated_name: { language_name: "arabic", name: "فاطر" } },
  { id: 36, name_arabic: "يس", name_simple: "Ya-Sin", verses_count: 83, revelation_place: "makkah", revelation_order: 41, bismillah_pre: true, name_complex: "Yā-Sīn", pages: [440, 445], translated_name: { language_name: "arabic", name: "يس" } },
  { id: 37, name_arabic: "الصافات", name_simple: "As-Saffat", verses_count: 182, revelation_place: "makkah", revelation_order: 56, bismillah_pre: true, name_complex: "Aṣ-Ṣāffāt", pages: [446, 452], translated_name: { language_name: "arabic", name: "الصافات" } },
  { id: 38, name_arabic: "ص", name_simple: "Sad", verses_count: 88, revelation_place: "makkah", revelation_order: 38, bismillah_pre: true, name_complex: "Ṣād", pages: [453, 458], translated_name: { language_name: "arabic", name: "ص" } },
  { id: 39, name_arabic: "الزمر", name_simple: "Az-Zumar", verses_count: 75, revelation_place: "makkah", revelation_order: 59, bismillah_pre: true, name_complex: "Az-Zumar", pages: [458, 467], translated_name: { language_name: "arabic", name: "الزمر" } },
  { id: 40, name_arabic: "غافر", name_simple: "Ghafir", verses_count: 85, revelation_place: "makkah", revelation_order: 60, bismillah_pre: true, name_complex: "Ghāfir", pages: [467, 476], translated_name: { language_name: "arabic", name: "غافر" } },
  { id: 41, name_arabic: "فصلت", name_simple: "Fussilat", verses_count: 54, revelation_place: "makkah", revelation_order: 61, bismillah_pre: true, name_complex: "Fuṣṣilat", pages: [477, 482], translated_name: { language_name: "arabic", name: "فصلت" } },
  { id: 42, name_arabic: "الشورى", name_simple: "Ash-Shura", verses_count: 53, revelation_place: "makkah", revelation_order: 62, bismillah_pre: true, name_complex: "Ash-Shūrā", pages: [483, 489], translated_name: { language_name: "arabic", name: "الشورى" } },
  { id: 43, name_arabic: "الزخرف", name_simple: "Az-Zukhruf", verses_count: 89, revelation_place: "makkah", revelation_order: 63, bismillah_pre: true, name_complex: "Az-Zukhruf", pages: [489, 495], translated_name: { language_name: "arabic", name: "الزخرف" } },
  { id: 44, name_arabic: "الدخان", name_simple: "Ad-Dukhan", verses_count: 59, revelation_place: "makkah", revelation_order: 64, bismillah_pre: true, name_complex: "Ad-Dukhān", pages: [496, 498], translated_name: { language_name: "arabic", name: "الدخان" } },
  { id: 45, name_arabic: "الجاثية", name_simple: "Al-Jathiyah", verses_count: 37, revelation_place: "makkah", revelation_order: 65, bismillah_pre: true, name_complex: "Al-Jāthiyah", pages: [499, 502], translated_name: { language_name: "arabic", name: "الجاثية" } },
  { id: 46, name_arabic: "الأحقاف", name_simple: "Al-Ahqaf", verses_count: 35, revelation_place: "makkah", revelation_order: 66, bismillah_pre: true, name_complex: "Al-Aḥqāf", pages: [502, 506], translated_name: { language_name: "arabic", name: "الأحقاف" } },
  { id: 47, name_arabic: "محمد", name_simple: "Muhammad", verses_count: 38, revelation_place: "madinah", revelation_order: 95, bismillah_pre: true, name_complex: "Muḥammad", pages: [507, 510], translated_name: { language_name: "arabic", name: "محمد" } },
  { id: 48, name_arabic: "الفتح", name_simple: "Al-Fath", verses_count: 29, revelation_place: "madinah", revelation_order: 111, bismillah_pre: true, name_complex: "Al-Fatḥ", pages: [511, 515], translated_name: { language_name: "arabic", name: "الفتح" } },
  { id: 49, name_arabic: "الحجرات", name_simple: "Al-Hujurat", verses_count: 18, revelation_place: "madinah", revelation_order: 106, bismillah_pre: true, name_complex: "Al-Ḥujurāt", pages: [515, 517], translated_name: { language_name: "arabic", name: "الحجرات" } },
  { id: 50, name_arabic: "ق", name_simple: "Qaf", verses_count: 45, revelation_place: "makkah", revelation_order: 34, bismillah_pre: true, name_complex: "Qāf", pages: [518, 520], translated_name: { language_name: "arabic", name: "ق" } },
  { id: 51, name_arabic: "الذاريات", name_simple: "Adh-Dhariyat", verses_count: 60, revelation_place: "makkah", revelation_order: 67, bismillah_pre: true, name_complex: "Adh-Dhāriyāt", pages: [520, 523], translated_name: { language_name: "arabic", name: "الذاريات" } },
  { id: 52, name_arabic: "الطور", name_simple: "At-Tur", verses_count: 49, revelation_place: "makkah", revelation_order: 76, bismillah_pre: true, name_complex: "Aṭ-Ṭūr", pages: [523, 525], translated_name: { language_name: "arabic", name: "الطور" } },
  { id: 53, name_arabic: "النجم", name_simple: "An-Najm", verses_count: 62, revelation_place: "makkah", revelation_order: 23, bismillah_pre: true, name_complex: "An-Najm", pages: [526, 528], translated_name: { language_name: "arabic", name: "النجم" } },
  { id: 54, name_arabic: "القمر", name_simple: "Al-Qamar", verses_count: 55, revelation_place: "makkah", revelation_order: 37, bismillah_pre: true, name_complex: "Al-Qamar", pages: [528, 531], translated_name: { language_name: "arabic", name: "القمر" } },
  { id: 55, name_arabic: "الرحمن", name_simple: "Ar-Rahman", verses_count: 78, revelation_place: "madinah", revelation_order: 97, bismillah_pre: true, name_complex: "Ar-Raḥmān", pages: [531, 534], translated_name: { language_name: "arabic", name: "الرحمن" } },
  { id: 56, name_arabic: "الواقعة", name_simple: "Al-Waqi'ah", verses_count: 96, revelation_place: "makkah", revelation_order: 46, bismillah_pre: true, name_complex: "Al-Wāqi'ah", pages: [534, 537], translated_name: { language_name: "arabic", name: "الواقعة" } },
  { id: 57, name_arabic: "الحديد", name_simple: "Al-Hadid", verses_count: 29, revelation_place: "madinah", revelation_order: 94, bismillah_pre: true, name_complex: "Al-Ḥadīd", pages: [537, 541], translated_name: { language_name: "arabic", name: "الحديد" } },
  { id: 58, name_arabic: "المجادلة", name_simple: "Al-Mujadila", verses_count: 22, revelation_place: "madinah", revelation_order: 105, bismillah_pre: true, name_complex: "Al-Mujādilah", pages: [542, 545], translated_name: { language_name: "arabic", name: "المجادلة" } },
  { id: 59, name_arabic: "الحشر", name_simple: "Al-Hashr", verses_count: 24, revelation_place: "madinah", revelation_order: 101, bismillah_pre: true, name_complex: "Al-Ḥashr", pages: [545, 548], translated_name: { language_name: "arabic", name: "الحشر" } },
  { id: 60, name_arabic: "الممتحنة", name_simple: "Al-Mumtahanah", verses_count: 13, revelation_place: "madinah", revelation_order: 91, bismillah_pre: true, name_complex: "Al-Mumtaḥanah", pages: [549, 551], translated_name: { language_name: "arabic", name: "الممتحنة" } },
  { id: 61, name_arabic: "الصف", name_simple: "As-Saff", verses_count: 14, revelation_place: "madinah", revelation_order: 109, bismillah_pre: true, name_complex: "Aṣ-Ṣaff", pages: [551, 552], translated_name: { language_name: "arabic", name: "الصف" } },
  { id: 62, name_arabic: "الجمعة", name_simple: "Al-Jumu'ah", verses_count: 11, revelation_place: "madinah", revelation_order: 110, bismillah_pre: true, name_complex: "Al-Jumu'ah", pages: [553, 554], translated_name: { language_name: "arabic", name: "الجمعة" } },
  { id: 63, name_arabic: "المنافقون", name_simple: "Al-Munafiqun", verses_count: 11, revelation_place: "madinah", revelation_order: 104, bismillah_pre: true, name_complex: "Al-Munāfiqūn", pages: [554, 555], translated_name: { language_name: "arabic", name: "المنافقون" } },
  { id: 64, name_arabic: "التغابن", name_simple: "At-Taghabun", verses_count: 18, revelation_place: "madinah", revelation_order: 108, bismillah_pre: true, name_complex: "At-Taghābun", pages: [556, 557], translated_name: { language_name: "arabic", name: "التغابن" } },
  { id: 65, name_arabic: "الطلاق", name_simple: "At-Talaq", verses_count: 12, revelation_place: "madinah", revelation_order: 99, bismillah_pre: true, name_complex: "At-Ṭalāq", pages: [558, 559], translated_name: { language_name: "arabic", name: "الطلاق" } },
  { id: 66, name_arabic: "التحريم", name_simple: "At-Tahrim", verses_count: 12, revelation_place: "madinah", revelation_order: 107, bismillah_pre: true, name_complex: "At-Taḥrīm", pages: [560, 561], translated_name: { language_name: "arabic", name: "التحريم" } },
  { id: 67, name_arabic: "الملك", name_simple: "Al-Mulk", verses_count: 30, revelation_place: "makkah", revelation_order: 77, bismillah_pre: true, name_complex: "Al-Mulk", pages: [562, 564], translated_name: { language_name: "arabic", name: "الملك" } },
  { id: 68, name_arabic: "القلم", name_simple: "Al-Qalam", verses_count: 52, revelation_place: "makkah", revelation_order: 2, bismillah_pre: true, name_complex: "Al-Qalam", pages: [564, 566], translated_name: { language_name: "arabic", name: "القلم" } },
  { id: 69, name_arabic: "الحاقة", name_simple: "Al-Haqqah", verses_count: 52, revelation_place: "makkah", revelation_order: 78, bismillah_pre: true, name_complex: "Al-Ḥāqqah", pages: [566, 568], translated_name: { language_name: "arabic", name: "الحاقة" } },
  { id: 70, name_arabic: "المعارج", name_simple: "Al-Ma'arij", verses_count: 44, revelation_place: "makkah", revelation_order: 79, bismillah_pre: true, name_complex: "Al-Ma'ārij", pages: [568, 570], translated_name: { language_name: "arabic", name: "المعارج" } },
  { id: 71, name_arabic: "نوح", name_simple: "Nuh", verses_count: 28, revelation_place: "makkah", revelation_order: 71, bismillah_pre: true, name_complex: "Nūḥ", pages: [570, 571], translated_name: { language_name: "arabic", name: "نوح" } },
  { id: 72, name_arabic: "الجن", name_simple: "Al-Jinn", verses_count: 28, revelation_place: "makkah", revelation_order: 40, bismillah_pre: true, name_complex: "Al-Jinn", pages: [572, 573], translated_name: { language_name: "arabic", name: "الجن" } },
  { id: 73, name_arabic: "المزمل", name_simple: "Al-Muzzammil", verses_count: 20, revelation_place: "makkah", revelation_order: 3, bismillah_pre: true, name_complex: "Al-Muzzammil", pages: [574, 575], translated_name: { language_name: "arabic", name: "المزمل" } },
  { id: 74, name_arabic: "المدثر", name_simple: "Al-Muddaththir", verses_count: 56, revelation_place: "makkah", revelation_order: 4, bismillah_pre: true, name_complex: "Al-Muddaththir", pages: [575, 577], translated_name: { language_name: "arabic", name: "المدثر" } },
  { id: 75, name_arabic: "القيامة", name_simple: "Al-Qiyamah", verses_count: 40, revelation_place: "makkah", revelation_order: 31, bismillah_pre: true, name_complex: "Al-Qiyāmah", pages: [577, 578], translated_name: { language_name: "arabic", name: "القيامة" } },
  { id: 76, name_arabic: "الإنسان", name_simple: "Al-Insan", verses_count: 31, revelation_place: "madinah", revelation_order: 98, bismillah_pre: true, name_complex: "Al-Insān", pages: [578, 580], translated_name: { language_name: "arabic", name: "الإنسان" } },
  { id: 77, name_arabic: "المرسلات", name_simple: "Al-Mursalat", verses_count: 50, revelation_place: "makkah", revelation_order: 33, bismillah_pre: true, name_complex: "Al-Mursalāt", pages: [580, 581], translated_name: { language_name: "arabic", name: "المرسلات" } },
  { id: 78, name_arabic: "النبأ", name_simple: "An-Naba", verses_count: 40, revelation_place: "makkah", revelation_order: 80, bismillah_pre: true, name_complex: "An-Naba'", pages: [582, 583], translated_name: { language_name: "arabic", name: "النبأ" } },
  { id: 79, name_arabic: "النازعات", name_simple: "An-Nazi'at", verses_count: 46, revelation_place: "makkah", revelation_order: 81, bismillah_pre: true, name_complex: "An-Nāzi'āt", pages: [583, 584], translated_name: { language_name: "arabic", name: "النازعات" } },
  { id: 80, name_arabic: "عبس", name_simple: "'Abasa", verses_count: 42, revelation_place: "makkah", revelation_order: 24, bismillah_pre: true, name_complex: "'Abasa", pages: [585, 585], translated_name: { language_name: "arabic", name: "عبس" } },
  { id: 81, name_arabic: "التكوير", name_simple: "At-Takwir", verses_count: 29, revelation_place: "makkah", revelation_order: 7, bismillah_pre: true, name_complex: "At-Takwīr", pages: [586, 586], translated_name: { language_name: "arabic", name: "التكوير" } },
  { id: 82, name_arabic: "الانفطار", name_simple: "Al-Infitar", verses_count: 19, revelation_place: "makkah", revelation_order: 82, bismillah_pre: true, name_complex: "Al-Infiṭār", pages: [587, 587], translated_name: { language_name: "arabic", name: "الانفطار" } },
  { id: 83, name_arabic: "المطففين", name_simple: "Al-Mutaffifin", verses_count: 36, revelation_place: "makkah", revelation_order: 86, bismillah_pre: true, name_complex: "Al-Muṭaffifīn", pages: [587, 589], translated_name: { language_name: "arabic", name: "المطففين" } },
  { id: 84, name_arabic: "الانشقاق", name_simple: "Al-Inshiqaq", verses_count: 25, revelation_place: "makkah", revelation_order: 83, bismillah_pre: true, name_complex: "Al-Inshiqāq", pages: [589, 590], translated_name: { language_name: "arabic", name: "الانشقاق" } },
  { id: 85, name_arabic: "البروج", name_simple: "Al-Buruj", verses_count: 22, revelation_place: "makkah", revelation_order: 27, bismillah_pre: true, name_complex: "Al-Burūj", pages: [590, 590], translated_name: { language_name: "arabic", name: "البروج" } },
  { id: 86, name_arabic: "الطارق", name_simple: "At-Tariq", verses_count: 17, revelation_place: "makkah", revelation_order: 36, bismillah_pre: true, name_complex: "At-Ṭāriq", pages: [591, 591], translated_name: { language_name: "arabic", name: "الطارق" } },
  { id: 87, name_arabic: "الأعلى", name_simple: "Al-A'la", verses_count: 19, revelation_place: "makkah", revelation_order: 8, bismillah_pre: true, name_complex: "Al-A'lā", pages: [591, 592], translated_name: { language_name: "arabic", name: "الأعلى" } },
  { id: 88, name_arabic: "الغاشية", name_simple: "Al-Ghashiyah", verses_count: 26, revelation_place: "makkah", revelation_order: 68, bismillah_pre: true, name_complex: "Al-Ghāshiyah", pages: [592, 592], translated_name: { language_name: "arabic", name: "الغاشية" } },
  { id: 89, name_arabic: "الفجر", name_simple: "Al-Fajr", verses_count: 30, revelation_place: "makkah", revelation_order: 10, bismillah_pre: true, name_complex: "Al-Fajr", pages: [593, 594], translated_name: { language_name: "arabic", name: "الفجر" } },
  { id: 90, name_arabic: "البلد", name_simple: "Al-Balad", verses_count: 20, revelation_place: "makkah", revelation_order: 35, bismillah_pre: true, name_complex: "Al-Balad", pages: [594, 595], translated_name: { language_name: "arabic", name: "البلد" } },
  { id: 91, name_arabic: "الشمس", name_simple: "Ash-Shams", verses_count: 15, revelation_place: "makkah", revelation_order: 26, bismillah_pre: true, name_complex: "Ash-Shams", pages: [595, 595], translated_name: { language_name: "arabic", name: "الشمس" } },
  { id: 92, name_arabic: "الليل", name_simple: "Al-Layl", verses_count: 21, revelation_place: "makkah", revelation_order: 9, bismillah_pre: true, name_complex: "Al-Layl", pages: [595, 596], translated_name: { language_name: "arabic", name: "الليل" } },
  { id: 93, name_arabic: "الضحى", name_simple: "Ad-Duha", verses_count: 11, revelation_place: "makkah", revelation_order: 11, bismillah_pre: true, name_complex: "Aḍ-Ḍuḥā", pages: [596, 596], translated_name: { language_name: "arabic", name: "الضحى" } },
  { id: 94, name_arabic: "الشرح", name_simple: "Ash-Sharh", verses_count: 8, revelation_place: "makkah", revelation_order: 12, bismillah_pre: true, name_complex: "Ash-Sharḥ", pages: [596, 596], translated_name: { language_name: "arabic", name: "الشرح" } },
  { id: 95, name_arabic: "التين", name_simple: "At-Tin", verses_count: 8, revelation_place: "makkah", revelation_order: 28, bismillah_pre: true, name_complex: "At-Tīn", pages: [597, 597], translated_name: { language_name: "arabic", name: "التين" } },
  { id: 96, name_arabic: "العلق", name_simple: "Al-'Alaq", verses_count: 19, revelation_place: "makkah", revelation_order: 1, bismillah_pre: true, name_complex: "Al-'Alaq", pages: [597, 598], translated_name: { language_name: "arabic", name: "العلق" } },
  { id: 97, name_arabic: "القدر", name_simple: "Al-Qadr", verses_count: 5, revelation_place: "makkah", revelation_order: 25, bismillah_pre: true, name_complex: "Al-Qadr", pages: [598, 598], translated_name: { language_name: "arabic", name: "القدر" } },
  { id: 98, name_arabic: "البينة", name_simple: "Al-Bayyinah", verses_count: 8, revelation_place: "madinah", revelation_order: 100, bismillah_pre: true, name_complex: "Al-Bayyinah", pages: [598, 599], translated_name: { language_name: "arabic", name: "البينة" } },
  { id: 99, name_arabic: "الزلزلة", name_simple: "Az-Zalzalah", verses_count: 8, revelation_place: "madinah", revelation_order: 93, bismillah_pre: true, name_complex: "Az-Zalzalah", pages: [599, 599], translated_name: { language_name: "arabic", name: "الزلزلة" } },
  { id: 100, name_arabic: "العاديات", name_simple: "Al-'Adiyat", verses_count: 11, revelation_place: "makkah", revelation_order: 14, bismillah_pre: true, name_complex: "Al-'Ādiyāt", pages: [599, 600], translated_name: { language_name: "arabic", name: "العاديات" } },
  { id: 101, name_arabic: "القارعة", name_simple: "Al-Qari'ah", verses_count: 11, revelation_place: "makkah", revelation_order: 30, bismillah_pre: true, name_complex: "Al-Qāri'ah", pages: [600, 600], translated_name: { language_name: "arabic", name: "القارعة" } },
  { id: 102, name_arabic: "التكاثر", name_simple: "At-Takathur", verses_count: 8, revelation_place: "makkah", revelation_order: 16, bismillah_pre: true, name_complex: "At-Takāthur", pages: [600, 600], translated_name: { language_name: "arabic", name: "التكاثر" } },
  { id: 103, name_arabic: "العصر", name_simple: "Al-'Asr", verses_count: 3, revelation_place: "makkah", revelation_order: 13, bismillah_pre: true, name_complex: "Al-'Aṣr", pages: [601, 601], translated_name: { language_name: "arabic", name: "العصر" } },
  { id: 104, name_arabic: "الهمزة", name_simple: "Al-Humazah", verses_count: 9, revelation_place: "makkah", revelation_order: 32, bismillah_pre: true, name_complex: "Al-Humazah", pages: [601, 601], translated_name: { language_name: "arabic", name: "الهمزة" } },
  { id: 105, name_arabic: "الفيل", name_simple: "Al-Fil", verses_count: 5, revelation_place: "makkah", revelation_order: 19, bismillah_pre: true, name_complex: "Al-Fīl", pages: [601, 601], translated_name: { language_name: "arabic", name: "الفيل" } },
  { id: 106, name_arabic: "قريش", name_simple: "Quraish", verses_count: 4, revelation_place: "makkah", revelation_order: 29, bismillah_pre: true, name_complex: "Quraysh", pages: [602, 602], translated_name: { language_name: "arabic", name: "قريش" } },
  { id: 107, name_arabic: "الماعون", name_simple: "Al-Ma'un", verses_count: 7, revelation_place: "makkah", revelation_order: 17, bismillah_pre: true, name_complex: "Al-Mā'ūn", pages: [602, 602], translated_name: { language_name: "arabic", name: "الماعون" } },
  { id: 108, name_arabic: "الكوثر", name_simple: "Al-Kawthar", verses_count: 3, revelation_place: "makkah", revelation_order: 15, bismillah_pre: true, name_complex: "Al-Kawthar", pages: [602, 602], translated_name: { language_name: "arabic", name: "الكوثر" } },
  { id: 109, name_arabic: "الكافرون", name_simple: "Al-Kafirun", verses_count: 6, revelation_place: "makkah", revelation_order: 18, bismillah_pre: true, name_complex: "Al-Kāfirūn", pages: [603, 603], translated_name: { language_name: "arabic", name: "الكافرون" } },
  { id: 110, name_arabic: "النصر", name_simple: "An-Nasr", verses_count: 3, revelation_place: "madinah", revelation_order: 114, bismillah_pre: true, name_complex: "An-Naṣr", pages: [603, 603], translated_name: { language_name: "arabic", name: "النصر" } },
  { id: 111, name_arabic: "المسد", name_simple: "Al-Masad", verses_count: 5, revelation_place: "makkah", revelation_order: 6, bismillah_pre: true, name_complex: "Al-Masad", pages: [603, 603], translated_name: { language_name: "arabic", name: "المسد" } },
  { id: 112, name_arabic: "الإخلاص", name_simple: "Al-Ikhlas", verses_count: 4, revelation_place: "makkah", revelation_order: 22, bismillah_pre: true, name_complex: "Al-Ikhlāṣ", pages: [604, 604], translated_name: { language_name: "arabic", name: "الإخلاص" } },
  { id: 113, name_arabic: "الفلق", name_simple: "Al-Falaq", verses_count: 5, revelation_place: "makkah", revelation_order: 20, bismillah_pre: true, name_complex: "Al-Falaq", pages: [604, 604], translated_name: { language_name: "arabic", name: "الفلق" } },
  { id: 114, name_arabic: "الناس", name_simple: "An-Nas", verses_count: 6, revelation_place: "makkah", revelation_order: 21, bismillah_pre: true, name_complex: "An-Nās", pages: [604, 604], translated_name: { language_name: "arabic", name: "الناس" } }
];

export const RECITERS: Reciter[] = [
  { id: 7, reciter_name: "مشاري راشد العفاسي", style: "Murattal", translated_name: { language_name: "arabic", name: "مشاري راشد العفاسي" } },
  { id: 1, reciter_name: "عبد الباسط عبد الصمد", style: "Murattal", translated_name: { language_name: "arabic", name: "عبد الباسط عبد الصمد" } },
  { id: 2, reciter_name: "عبد الباسط عبد الصمد", style: "Mujawwad", translated_name: { language_name: "arabic", name: "عبد الباسط عبد الصمد" } },
  { id: 3, reciter_name: "عبد الرحمن السديس", style: "Murattal", translated_name: { language_name: "arabic", name: "عبد الرحمن السديس" } },
  { id: 4, reciter_name: "محمود خليل الحصري", style: "Murattal", translated_name: { language_name: "arabic", name: "محمود خليل الحصري" } },
  { id: 5, reciter_name: "محمد صديق المنشاوي", style: "Murattal", translated_name: { language_name: "arabic", name: "محمد صديق المنشاوي" } },
  { id: 6, reciter_name: "ماهر المعيقلي", style: "Murattal", translated_name: { language_name: "arabic", name: "ماهر المعيقلي" } },
  { id: 12, reciter_name: "ياسر الدوسري", style: "Murattal", translated_name: { language_name: "arabic", name: "ياسر الدوسري" } },
  { id: 8, reciter_name: "سعد الغامدي", style: "Murattal", translated_name: { language_name: "arabic", name: "سعد الغامدي" } },
  { id: 9, reciter_name: "أحمد بن علي العجمي", style: "Murattal", translated_name: { language_name: "arabic", name: "أحمد بن علي العجمي" } },
  { id: 10, reciter_name: "سعود الشريم", style: "Murattal", translated_name: { language_name: "arabic", name: "سعود الشريم" } },
  { id: 11, reciter_name: "محمد أيوب", style: "Murattal", translated_name: { language_name: "arabic", name: "محمد أيوب" } }
];
